import type { Report, State } from "./types";

let csrf = "";
const displayRequests = new Map<string, Promise<Report>>();
const frontendCalls = { frontend_api_calls: 0, frontend_provider_calls: 0 };
const PROVIDER_MARKERS = [
  "mainnet.helius-rpc.com",
  "public-api.birdeye.so",
  "api.mainnet-beta.solana.com",
  "api.jup.ag",
];
export function frontendInstrumentation() {
  return { ...frontendCalls };
}
export function noteFrontendUrl(url: string) {
  if (PROVIDER_MARKERS.some((marker) => url.includes(marker))) frontendCalls.frontend_provider_calls += 1;
}
export async function bootstrap() {
  const params = new URLSearchParams(location.hash.slice(1));
  const token = params.get("session");
  const response = await fetch("/api/bootstrap", {
    headers: token ? { "X-Launch-Token": token } : {},
    credentials: "same-origin",
  });
  if (!response.ok)
    throw new Error(
      "This browser session could not be authenticated. Open the address generated by the local launcher.",
    );
  const result = await response.json();
  csrf = result.csrf;
  if (token)
    history.replaceState(null, "", location.pathname + location.search);
  return result;
}
export async function api<T = unknown>(
  path: string,
  method = "GET",
  body?: unknown,
): Promise<T> {
  frontendCalls.frontend_api_calls += 1;
  const response = await fetch(`/api${path}`, {
    method,
    credentials: "same-origin",
    headers: {
      "Content-Type": "application/json",
      ...(method !== "GET" ? { "X-CSRF-Token": csrf } : {}),
    },
    ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
  });
  if (!response.ok) {
    const payload = await response.json().catch(() => ({}));
    const detail = payload.detail;
    throw new Error(
      typeof detail === "string"
        ? detail
        : detail
          ? JSON.stringify(detail)
          : `Request failed (${response.status})`,
    );
  }
  return response.status === 204 ? (undefined as T) : response.json();
}

export function workspaceSummary(): Promise<State> {
  return api<State>("/state?report_view=summary");
}

export function reportDisplay(id: string): Promise<Report> {
  const pending = displayRequests.get(id);
  if (pending) return pending;
  const request = api<Report>(`/reports/${encodeURIComponent(id)}?view=display`)
    .finally(() => {
      if (displayRequests.get(id) === request) displayRequests.delete(id);
    });
  displayRequests.set(id, request);
  return request;
}

export function loadReportDisplay(report: Report): Promise<Report> {
  return report.report_view?.view === "display"
    ? Promise.resolve(report)
    : reportDisplay(report.id);
}

export async function uploadArchive(file: File): Promise<{ report_id: string }> {
  const response = await fetch('/api/archives/import', {
    method: 'POST', credentials: 'same-origin',
    headers: { 'Content-Type': 'application/zip', 'X-CSRF-Token': csrf },
    body: file,
  });
  const result = await response.json();
  if (!response.ok) throw new Error(typeof result.detail === 'string' ? result.detail : `Import failed (${response.status})`);
  return result;
}
